# Generated by Django 3.1.4 on 2020-12-09 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Basics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('county', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('role', models.CharField(max_length=200, null=True)),
                ('sector', models.CharField(max_length=200, null=True)),
                ('seeking_work', models.BooleanField(default=True)),
                ('avatar', models.ImageField(default='avatar.jpg', upload_to='avatars/')),
                ('cover', models.ImageField(default='avatar.jpg', upload_to='covers/')),
                ('fun_fact', models.CharField(blank=True, max_length=2000, null=True)),
                ('achievement', models.CharField(blank=True, max_length=2000, null=True)),
                ('hobbies', models.CharField(blank=True, max_length=2000, null=True)),
                ('favourite_quote', models.CharField(blank=True, max_length=2000, null=True)),
                ('contract_length', models.CharField(blank=True, max_length=2000, null=True)),
                ('remote_employee', models.BooleanField(blank=True, default=True)),
                ('travel_distance', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('liked', models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_title', models.CharField(max_length=200, null=True)),
                ('education_level', models.CharField(max_length=200, null=True)),
                ('subject', models.CharField(max_length=200, null=True)),
                ('institution_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_of_skill', models.CharField(max_length=200, null=True)),
                ('name_of_skill', models.CharField(max_length=200, null=True)),
                ('level_of_skill', models.CharField(max_length=200, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Work_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_under', models.CharField(max_length=200, null=True)),
                ('role_name', models.CharField(max_length=200, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employer_Basics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('sector', models.CharField(max_length=200, null=True)),
                ('about', models.CharField(max_length=2000, null=True)),
                ('culture', models.CharField(max_length=2000, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('county', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('logo', models.ImageField(default='avatar.jpg', upload_to='avatars/')),
                ('employer_cover', models.ImageField(default='avatar.jpg', upload_to='covers/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('slug2', models.SlugField(blank=True, unique=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow_Employers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Not following', 'Not following'), ('Following', 'Following')], max_length=30)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='jobseeker.employer_basics')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='jobseeker.employee_basics')),
            ],
        ),
    ]
