# Generated by Django 3.1.4 on 2020-12-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_basics',
            name='current_company',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
