# Generated by Django 3.1.4 on 2020-12-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_employee_basics_current_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_basics',
            name='bio',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
